/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/no-explicit-any */
import React from 'react';
import { Page, Text, View, Document, StyleSheet, Image } from '@react-pdf/renderer';

// Create styles (CSS-in-JS specifically for PDF)
const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#ffffff',
    padding: 40,
  },
  header: {
    marginBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#cccccc',
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
  },
  subtitle: {
    fontSize: 12,
    color: '#666666',
    marginTop: 5,
  },
  section: {
    margin: 10,
    padding: 10,
    flexGrow: 1,
  },
  metricRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomStyle: 'dashed',
    borderBottomColor: '#eeeeee',
    paddingBottom: 5,
  },
  metricLabel: {
    fontSize: 14,
    color: '#444444',
  },
  metricValue: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    color: '#888888',
    fontSize: 10,
  },
});

// The Component
export const ReportDocument = ({ data }: { data: any }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      
      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.title}>{data.title}</Text>
        <Text style={styles.subtitle}>
          Prepared for {data.project.client.name} • {data.month}
        </Text>
      </View>

      {/* Metrics Section */}
      <View style={styles.section}>
        <Text style={{ fontSize: 18, marginBottom: 20 }}>Key Performance Indicators</Text>
        
        <View style={styles.metricRow}>
          <Text style={styles.metricLabel}>Total Website Visits</Text>
          <Text style={styles.metricValue}>{data.content.visits?.toLocaleString()}</Text>
        </View>

        <View style={styles.metricRow}>
          <Text style={styles.metricLabel}>New Leads Generated</Text>
          <Text style={styles.metricValue}>{data.content.leads?.toLocaleString()}</Text>
        </View>

        <View style={styles.metricRow}>
          <Text style={styles.metricLabel}>Conversion Rate</Text>
          <Text style={styles.metricValue}>{data.content.conversion}%</Text>
        </View>
      </View>

      {/* Footer */}
      <Text style={styles.footer}>
        Generated by AgencyCRM • Confidential Report
      </Text>
    </Page>
  </Document>
);