// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // Use DIRECT_URL (Session Mode pooler, port 5432) for migrations
    // Session mode supports prepared statements, Transaction mode (6543) doesn't
    url: process.env['DIRECT_URL'],
  },
});
